### ISSUE TITLE
Sign a url prefix

### ISSUE THREAD

**Issue by pablopla** [minio/nginx-minio-plugins#4]
It will be useful to be able to sign a url prefix.
For example, a signature for http://myminio/website/5/ will let a user download all objects under this prefix with the same signature.

To prevent accessing all the objects with a single wildcard signature, a developer can define with nginx directive what prefix is allowed. For example I might want to allow /website/-website-/ but not the root prefix /

**Comment by harshavardhana** [comment]
Closing this since this will be implemented as part of minio server.
